stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  image: node
  script:
    - npm install
  artifacts:
    paths:
      - .node_modules
      - package-lock.json

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:  
    - npm run build
  artifacts:
    paths:
      - .next


deploy:
  stage: deploy
  image: node
  script:
  - npm run dev > /dev/null 2>&1 &
  