stages:
  - install
  - lint
  - build
  - deploy

install:
  stage: install
  script:
    - brew update 
    - brew install npm 
    - npm install
  artifacts:
    paths:
      - .node_modules/
      - package-lock.json

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:  
    - npm run build
  artifacts:
    paths:
      - .next


deploy:
  stage: deploy
  script:
  - brew upadte 
  - brew install nodejs
  - npm run dev

  