stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

install:
  stage: install
  script:
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - brew update 
    - brew install npm 
    - npm run build
  artifacts:
    paths:
      - .next


deploy:
  stage: deploy
  script:
  -  brew upadte 
  - brew install nodejs
  - npm run dev
  - echo "Deploying to production..."
    # Add your deployment commands here
  
  environment:
    name: production
    url: https://your-production-url.com
  only:
    - main