import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppWrapper } from '@/context';
import Sidebar from './components/ui/Sidebar';
// import { headers } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const headersList = headers();
  const isAuthPage = false;
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          {isAuthPage ? (
            <>{children}</>
          ) : (
            <div className="container">
              <Sidebar />
              <main>{children}</main>
            </div>
          )}
        </AppWrapper>
      </body>
    </html>
  );
}
