import React from 'react';
import type { Metadata } from 'next';

import '../globals.css';
import Header from '../components/ui/Header';
import Sidebar from '../components/ui/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Sidebar />
      <main style={{ marginLeft: '20rem' }}>{children}</main>
    </>
  );
}
